port: 55
server:
  port: 2001
  context-path: /
eureka:
  instance:
    hostname: localhost #eureka注册中心实例名称
  client:
    register-with-eureka: false #false 由于该应用为服务注册中心，所以设置为false,代表不向注册中心注册自己。
    fetch-registry: true     #true 由于注册中心要查询到服务实例，它需要去检索服务，所以设置为true
